export const ukPlanFeatures = {
  essentials: [
    { name: 'Single-user access', included: true },
    { name: 'Meeting uploads: 10 per month', included: true },
    { name: 'Evidence-linked notes', included: true },
    { name: 'FCA review-ready documentation', included: true },
    { name: 'Export: PDF + CSV', included: true },
    { name: 'Email support', included: true },
    { name: 'API access', included: false },
    { name: 'Team roles & permissions', included: false },
    { name: 'Custom retention policies', included: false },
    { name: 'Dedicated account manager', included: false },
  ],
  professional: [
    { name: 'Up to 10 users', included: true },
    { name: 'Meeting uploads: 50 per month', included: true },
    { name: 'Evidence-linked notes', included: true },
    { name: 'FCA review-ready documentation', included: true },
    { name: 'Export: PDF + CSV + ZIP bundles', included: true },
    { name: 'Priority support', included: true },
    { name: 'API access', included: true },
    { name: 'Team roles & permissions', included: true },
    { name: 'Custom retention policies', included: true },
    { name: 'Dedicated account manager', included: true },
  ],
  enterprise: [
    { name: 'Everything in Professional', included: true },
    { name: 'CRM integration (Wealthbox/Redtail/Salesforce)', included: true },
    { name: 'SSO', included: true },
    { name: 'Multi-branch supervision workflows', included: true },
    { name: 'Custom retention mappings', included: true },
    { name: 'Dedicated onboarding', included: true },
  ],
  essentialsDescription: 'For individual UK financial advisers',
  professionalDescription: 'For growing UK financial services firms',
  enterpriseDescription: 'For multi-branch RIA firms',
}
