export const usPlanFeatures = {
  essentials: [
    { name: 'Single-user access', included: true },
    { name: 'Meeting uploads: 10 per month', included: true },
    { name: 'Evidence-linked notes', included: true },
    { name: 'SEC-ready documentation', included: true },
    { name: 'Export: PDF + CSV', included: true },
    { name: 'Email support', included: true },
    { name: 'API access', included: false },
    { name: 'Team roles & permissions', included: false },
    { name: 'Custom retention policies', included: false },
    { name: 'Dedicated account manager', included: false },
  ],
  professional: [
    { name: 'Up to 10 users', included: true },
    { name: 'Meeting uploads: 50 per month', included: true },
    { name: 'Evidence-linked notes', included: true },
    { name: 'SEC-ready documentation', included: true },
    { name: 'Export: PDF + CSV + ZIP bundles', included: true },
    { name: 'Priority support', included: true },
    { name: 'API access', included: true },
    { name: 'Team roles & permissions', included: true },
    { name: 'Custom retention policies', included: true },
    { name: 'Dedicated account manager', included: true },
  ],
  enterprise: [
    { name: 'Everything in Professional', included: true },
    { name: 'Multi-client CCO workspace', included: true },
    { name: 'Custom retention mappings', included: true },
    { name: 'Dedicated onboarding', included: true },
    { name: 'CRM integrations (roadmap)', included: false },
    { name: 'Single sign-on (roadmap)', included: false },
  ],
  essentialsDescription: 'For individual RIA advisors',
  professionalDescription: 'For growing RIA practices',
  enterpriseDescription: 'For multi-branch RIA firms and partner CCOs',
}
